name: Docker Image CI

on: #workflow_dispatch
  push:
    branches: [ "main" ]
    paths: [ "be-app/**" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag lklaric/homelab:$(date +%s)

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          lklaric/tc-be-app
        tags: |
          type=sha,enable=true,priority=100,prefix=,suffix=,format=short

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./be-app
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
