name: Frontend Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "fe-app/**" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag lklaric/homelab:$(date +%s)

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          lklaric/tc-fe-app
        tags: |
          type=sha,enable=true,priority=100,prefix=,suffix=,format=short

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./fe-app
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Add SHORT_SHA env property with commit short sha
        id: meta
        run: echo "short_sha=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_OUTPUT

      - name: Check TAG
        run: |
          echo ${{ steps.meta.outputs.short_sha }}

      - name: Terraform execution
        run: |
          #export TF_LOG=TRACE
          export TF_VAR_client_certificate=${{ secrets.CLIENT_CERTIFICATE }}
          export TF_VAR_client_key=${{ secrets.CLIENT_KEY }}
          export TF_VAR_cluster_ca_certificate=${{ secrets.CLUSTER_CA_CERTIFICATE }}
          export TF_VAR_image_tag=${{ steps.meta.outputs.short_sha }}
          cd tf-fe
          terraform init -reconfigure -backend-config=path="../../../tfstate/dev.fe.tfstate"
          terraform apply -auto-approve -var="app_part_short=fe"
