name: Deploy Frontend QA

on:  workflow_dispatch

jobs:
  setup_infra:
    runs-on: self-hosted

    steps:
        - uses: actions/checkout@v3

        - name: Terraform execution
          run: |
            #export TF_LOG=TRACE
            export TF_VAR_client_certificate=${{ secrets.CLIENT_CERTIFICATE }}
            export TF_VAR_client_key=${{ secrets.CLIENT_KEY }}
            export TF_VAR_cluster_ca_certificate=${{ secrets.CLUSTER_CA_CERTIFICATE }}
            #export TF_VAR_image_tag=${{ steps.meta.outputs.short_sha }}
            cd tf-infra
            terraform init -reconfigure -backend-config=path="../../../tfstate/infra.tfstate"
            terraform apply -auto-approve