name: Remove all environments

on:  workflow_dispatch

jobs:
  remove_ens:
    runs-on: self-hosted

    steps:
        - uses: actions/checkout@v3

        - name: Terraform execution
          run: |
            #export TF_LOG=TRACE
            export TF_VAR_client_certificate=${{ secrets.CLIENT_CERTIFICATE }}
            export TF_VAR_client_key=${{ secrets.CLIENT_KEY }}
            export TF_VAR_cluster_ca_certificate=${{ secrets.CLUSTER_CA_CERTIFICATE }}
            #export TF_VAR_image_tag=${{ steps.meta.outputs.short_sha }}
            cd tf-app

            terraform init -reconfigure -backend-config=path="../../../tfstate/dev.fe.tfstate"
            terraform destroy -auto-approve -var="app_part_short=fe"

            #terraform init -reconfigure -backend-config=path="../../../tfstate/prod.be.tfstate"
            #terraform destroy -auto-approve -var="app_part_short=be" -var="env=prod"

            #terraform init -reconfigure -backend-config=path="../../../tfstate/qa.fe.tfstate"
            #terraform destroy -auto-approve -var="app_part_short=fe" -var="env=qa"

            #terraform init -reconfigure -backend-config=path="../../../tfstate/qa.be.tfstate"
            #terraform destroy -auto-approve -var="app_part_short=be" -var="env=qa"